config/routes.rb
FirehoseApp::Application.routes.draw do

  root 'static_pages#index'

resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, ImageUploader

validates :lesson, :presence => true,
:numericality => {:less_than_or_equal_to => 100}

validates :emotion, :presence => true
validates :learned, :presence => true
validates :image, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

def destroy
	Pic.destroy(params[:id])
redirect_to pics_path
end

def show
	@pic = Pic.find(params[:id])
end
	def create
		# Pic.create(:lesson => 1, ...)
		@pic = Pic.create( pic_params )
		if @pic.valid?
			redirect_to pics_path
		else
			render :new, :status => :unprocessable_entity
		end
	end

	def new
		@pic = Pic.new
	end


	def index
		@pics = Pic.all
	end

	private

	def pic_params
		params.require(:pic).permit(:lesson, :emotion, :learned, :image)

	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def index
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar">
   <div class="navbar navbar-inverse">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
     <%= link_to 'Firehose App', root_path, :class=> 'brand' %>
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
    </div>
     <ul class="nav">
     	<li>
<%= link_to 'My App', pics_path %>
<%= link_to 'Your App', new_pic_path %>
     	</li>
    </div>
    </div>
    </div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
	<% @pics.each do |pic|  %>
	<div class="stolen-frosty span5 text-center">
<h1 class="stolen-h1">
		Lesson: <%= pic.lesson %>
</h1>
<br/>
<%= link_to pic_path(pic) do %>

<%= image_tag pic.image %>

<% end -%>

<h2>
Emotion: <%= pic.emotion %>
</h2>
<br/>
<h2>
Learned: <%= pic.learned %>
</h2>
<br/>
</div>
<% end %>

app/views/pics/new.html.erb
<h1 class="stolen-h1 span4 offset5 text-center">
	Save Your Lesson
	</h1>
<div class="stolen-frosty span4 offset5 text-center">


<%= simple_form_for @pic do |f| %>

<br>
<h2>
	<%= f.input :lesson , label: 'Which Lesson?'%>
	
	<%= f.input :image , label: 'Upload Your Image'%>
<br>
	<%= f.input :emotion , label: 'How did you feel?', placeholder: 'Stoked, Jazzed, Super' %>
	<%= f.input :learned , label: 'What did you learn?', placeholder: 'HTML, CSS, Rails, GitHub, Ruby' %>
</h2>

	<%= submit_tag 'Save', :class => 'btn btn-success btn-large' %>

<% end %>

</h2>
</div>

app/views/pics/show.html.erb
<div class="stolen-frosty span6 offset3 text-center">
	<h1 class="stolen-h1">Hello</h1>
	
</div>

app/views/static_pages/index.html.erb
<div class="stolen-frosty span6 offset3 text-center">

<h1 class="stolen-h1">Hi I'm Jeremy</h1>
	
<br/>
<%= image_tag @pic.image %>

<h2>
	I felt: <%= @pic.emotion %>
</h2>
<h2>
I learned: <%= @pic.learned %>
	</h2>

<%= link_to 'Back', pics_path, :class => 'btn btn-large btn-warning' %>

<%= link_to 'Delete', pick_path(@pic), :method => :delete, :class => 'btn btn-large btn-danger', :confirm => 'Your sure you wanna delete this?' %>
<br/>
<br/>
<%= link_to 'Launch', pics_path, :class => 'btn btn-warning btn-large'  %>

</div>